trigger:
- none

resources:
- repo: self

variables:
- group: "terraform-backend"

stages:
- stage: terraform
  displayName: Terraform
  jobs:  
  - job: run_bash
    displayName: Run bash
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: subscription
        scriptType: bash
        scriptPath: terraform.sh
        scriptArguments: "--action=$(terraform-action) --module=$(terraform-module) --backend-secret=$(AKSCOMM_TF_BACKEND_CLIENT_SECRET) --workspace=$(terraform-workspace)"
        addSpnToEnvironment: true
